# Generated by Django 3.0.7 on 2020-06-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=35)),
                ('ApellidoMaterno', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('Dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('Presentacion', models.CharField(max_length=35)),
                ('FechaVencimiento', models.DateTimeField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVenta', models.DateTimeField(auto_now=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.Cliente')),
                ('Productos', models.ManyToManyField(through='Venta.DetalleVenta', to='Venta.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.Producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.Venta'),
        ),
    ]
